### ISSUE TITLE
Regular flash toggle doesn't work when TrollLEDs is running in the background

### ISSUE THREAD

**Issue by onestok7208** [PoomSmart/TrollLEDs#2]
Device: iPhone SE (2016)
iOS version: 14.8
Issue: The system flash toggle does not work when TrollLEDs is running in the background. Also the entire camera app is broken

**Comment by PoomSmart** [comment]
Addressed in v1.2.0

It's the limitation with how TrollLEDs works. This version added the lock switch to mitigate the issue.

**Comment by plus024** [comment]
Can there be an option for TrollLEDs to automatically stop using the flashlight upon exiting the app (similar to how the magnifier app does)? I think it'd be a better solution than having to manually lock/force close everytime
