### ISSUE TITLE
1.3.1 Crash on iOS 16.6.1

### ISSUE THREAD

**Issue by sharklatan** [PoomSmart/TrollLEDs#3]
iPhone12,5
iPhone 11 Pro Max
16.6.1

unsandbox

https://github.com/PoomSmart/TrollLEDs/assets/5210221/f5ff4026-c65b-4709-83f0-b0002fdc7c3d

COMPARATIVE
Unsandbox 👉 ❌ it does not work

Sandbox 👉 ✅ Works

**Comment by PoomSmart** [comment]
I reuploaded the unsandboxed version that fixes this issue.
