### ISSUE TITLE
[Feature Request] Shortcut enhancements

### ISSUE THREAD

**Issue by theoccurrence** [PoomSmart/TrollLEDs#7]
I really love how I can control the LEDs with the Shortcuts app now. It's almost perfect. There are just three small enhancements that would make it truly perfect (for me).

1. Please add this toggle (if possible). Not forcing the app to open when activating the LEDs would be very appreciated.

![image](https://github.com/PoomSmart/TrollLEDs/assets/16444679/a646dd5a-9d89-423f-802c-cec65b39b591)

2. Please let us turn the LEDs off with a shortcut action. Seems like an oversight to only be able to turn them on.

3. The shortcuts implementation would really profit if you could pass values as parameters, to set the LEDs to exact values. This change increases the shortcut capabilities from 3 possible states to over 4 billion possible states.

**Comment by PoomSmart** [comment]
@theoccurrence The first one is apparently not possible. This feature needs an app with proper entitlements to control the LEDs. The other two are addressed in v1.8.0

**Comment by theoccurrence** [comment]
> @theoccurrence The first one is apparently not possible. This feature needs an app with proper entitlements to control the LEDs. 

I already feared this would be the case. It's really no big problem tho.

> The other two are addressed in v1.8.0

You are the GOAT! The app is now borderline perfect for what it does.

Tiny bit off topic: Are you working on an update for Amber by any chance? Or does it have the same problem why you couldn't implement request #1?

**Comment by PoomSmart** [comment]
@theoccurrence Not sure what you mean by Amber tweak having the same issue with #1 - the tweak doesn't come as an application.

**Comment by wkekdkd** [comment]
After I used this software, my system flashlight didn't respond. What's going on?
